on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          token: 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
          docker_name: ghcr.io/zaproxy/zaproxy:stable
          issue_title: ZAP Full Scan Report
          fail_action: false
          allow_issue_writing: true
          artifact_name: zap_scan
          target: 'https://www.paldeck.nl'
